# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb90cff28aa95dbc0b2ab25c25d23fa2e4b8af61bdae49521cc5ae0f49ed6058aa70703c3406e16acbf22a7ebd79e5b9dd78df21db927813b42549f910c6acd

test:
  secret_key_base: d9e43743870da71431ee8873894cd0dc09f68990b1e8206f7822182b49b4a30fa82bd21506614d06be5a74562e5a809862b379a56f9b3890638204a7d56470b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
